# Generated by Django 4.1.9 on 2023-06-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="date_updated",
        ),
        migrations.AddField(
            model_name="equipment",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
