# Generated by Django 4.1.9 on 2023-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipments", "0002_remove_equipment_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="status",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="location",
            field=models.CharField(
                choices=[("Warehouse", "Warehouse"), ("Facility", "Facility")],
                default="Warehouse",
                max_length=50,
                verbose_name="Current location",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(help_text="The name of the equipment", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="For large equipments, please provide the serial number",
                max_length=50,
                null=True,
            ),
        ),
    ]
