# Generated by Django 4.1.9 on 2023-06-07 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipments", "0007_rename_equipment_warehousestock_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="location",
        ),
    ]
