# Generated by Django 4.1.9 on 2023-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipments", "0008_remove_stock_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
