# Generated by Django 4.1.9 on 2023-06-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipments", "0009_alter_stock_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="district",
            field=models.CharField(default="Lilongwe", max_length=50),
        ),
    ]
